// TraceMap's configuration for the Sandcastle feature-PR workflow.
// The orchestration lives in @copperbox/sandcastle-workflow; everything
// repo-specific is set here. Unset fields use the package defaults
// (see FeatureFlowConfig).

import { defineConfig } from "@copperbox/sandcastle-workflow";

export default defineConfig({
  verifyCommand: "npm run typecheck && npm run test",

  // graphify-out/ is machine-generated by `graphify update` and always
  // considered good; keep it out of the reviewer's diff.
  review: { diffExcludes: ["graphify-out/**"] },

  // The sandbox image (.sandcastle/Dockerfile) pre-bakes headless Chromium and
  // its OS deps; tell the implementer how to use it and, crucially, what NOT
  // to attempt.
  implementNotes: `## Verifying UI changes

If your change affects the web UI and you want to confirm it end-to-end, a
headless Chromium and **all of its OS dependencies are already installed** in
this sandbox. The browser lives at the path in env \`PLAYWRIGHT_BROWSERS_PATH\`,
and the matching Playwright version is in env \`PLAYWRIGHT_VERSION\`. To drive the
app:

1. Add only the Playwright JS package (the browser itself is already downloaded):
   \`npm i -D playwright@$PLAYWRIGHT_VERSION\`
2. Start the dev server (e.g. \`npx vite\` in \`web/\`) and drive it with a short
   script, mocking \`/api/topology\` as needed.

Do **NOT** run \`playwright install-deps\`, download \`.deb\` packages, fetch system
libraries, or otherwise bootstrap a browser by hand — that is already done, and
attempting it will burn your entire context window. If UI verification still
fails for any reason, fall back to \`npm run typecheck\` + \`npm run test\`, note the
blocker in your commit message, and move on. Never spend the run fighting
browser setup.`,
});
